spring:
  application:
    name: still-no-name-project
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/coach_schema"
    username: "root"
    password: "1234"
  data:
    jdbc:
      dialect: mysql
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  app:
    name: "Still no name app"
    description: "App developed for learning purposes"
    version: "1.0"

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace